### ISSUE TITLE
Adding support for accounts outside of the EU

### ISSUE THREAD

**Issue by zanix** [timniklas/hass-neakasa#11]
When trying to provide my login credentials, I am met with this error.

```
Unknown error occurred
```

Log

```
2024-12-06 17:21:57.140 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 480, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 414, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        flow, cur_step["step_id"], user_input
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neakasa/config_flow.py", line 29, in async_step_user
    await api.connect(self._username, self._password)
  File "/config/custom_components/neakasa/api.py", line 30, in connect
    self._ali_authentication_token = await self._getAuthToken(username, password)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neakasa/api.py", line 63, in _getAuthToken
    return response_json['data']['user_info']['ali_authentication_token']
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

I then started to look into the code. I found this in `api.py`.

```python
    async def _getAuthToken(self, username: str, password: str):
        try:
            timestamp = str(int(time.time()))
            signature_raw = hmac.new(self._app_secret.encode(), (self._app_key + timestamp).encode(), digestmod=hashlib.sha256)
            signature = base64.b64encode(signature_raw.digest()).decode("utf-8")
            async with self._session.post(
                url='https://eu.neakasa.com/api/login/user',
...
```

I changed the url to `https://us.neakasa.com/api/login/user`, restarted HA, and got the same error.
I then tried to replicate the API call in Postman.

Pre-request script:

```js
const timestamp = Math.floor(Date.now() / 1000).toString();

const appKey = pm.environment.get("app_key"); // Retrieve App Key from environment variable
const appSecret = pm.environment.get("app_secret"); // Retrieve App Secret from environment variable

if (!appKey || !appSecret) {
  console.error("Error: App Key and App Secret are required environment variables.");
  pm.sendRequest.abort(); // Abort request if credentials are missing
}

const CryptoJS = require('crypto-js');

const signature = CryptoJS.HmacSHA256(appKey + timestamp, appSecret)
    .toString(CryptoJS.enc.Base64);
pm.environment.set("signature", signature);

pm.request.headers.add({key: "Request-Id", value: signature});
pm.request.headers.add({key: "Appid", value: appKey});
pm.request.headers.add({key: "Timestamp", value: timestamp});
pm.request.headers.add({key: "Sign", value: signature});
```

Body:

```json
{
    "product_id": "a123nCqsrQm3vEbt",
    "system": 2,
    "system_version": "Android14,SDK:34",
    "system_number": "GOOGLE_sdk_gphone64_x86_64-userdebug 14 UE1A.230829.050 12077443 dev-keys_sdk_gphone64_x86_64",
    "app_version": "2.0.9",
    "account": "*****",
    "type": 3,
    "password": "*****"
}
```

I got this response

```json
{
    "request_id": "9+OBanIB5qRaGMogA18YHKkY1H0DFN+lkRq+siGbWp4=",
    "code": 1009,
    "message": "ParamError：Key: 'LoginUserRequest.Password' Error:Field validation for 'Password' failed on the 'md5' tag",
    "data": null
}
```

I then tried to encode my password as a md5 hash, then I got this response

```json
{
    "request_id": "PryYLZ45yykTroJsLAfxxZoaNcVTRM5khoXFN2FnlIw=",
    "code": 3021,
    "message": "LoginError",
    "data": null
}
```

I'm not sure where to go from here. I hope this is enough information to figure this issue out.

**Comment by Fragilant** [comment]
Bump. Same issue here...

**Comment by timniklas** [comment]
I‘ll look into it, unfortunately i only tested with my EU accounts yet.

**Comment by torquadon** [comment]
I have a similar issue with an account created via an app in the UK.

**Comment by timniklas** [comment]
should be fixed in upcoming release

**Comment by torquadon** [comment]
Unfortunately, I still have the issue after installing 1.0.1

**Comment by zanix** [comment]
I also have the same issue after updating to 1.0.1.
I updated my Postman script to call the account lookup to get the API URL and that part works.

Response:

```json
{
    "request_id": "6440a16c-d6ad-4ab3-8d26-f206ffe47a55",
    "code": 0,
    "message": "success",
    "data": {
        "fault": "https://us.neakasa.com/fault",
        "op": "https://us.neakasa.com/api/",
        "web": "https://us.neakasa.com/api"
    }
}
```

It returns the same API URL I tried last time. However, I still get the same md5 error when the password is sent normally.

```json
{
    "request_id": "9+OBanIB5qRaGMogA18YHKkY1H0DFN+lkRq+siGbWp4=",
    "code": 1009,
    "message": "ParamError：Key: 'LoginUserRequest.Password' Error:Field validation for 'Password' failed on the 'md5' tag",
    "data": null
}
```

And if I md5 encode it, I get the `LoginError`.

```json
{
    "request_id": "12ZMx82swA7PrMNfoiEW+KZ2mNBIPBnPb4uGv2WWl7g=",
    "code": 3021,
    "message": "LoginError",
    "data": null
}
```

**Comment by JCPlex81** [comment]
Bump, also having the issue on latest version in US.

**Comment by timniklas** [comment]
I have created a US account and unfortunately I am not able to reproduce the error.

**Comment by timniklas** [comment]
It was a hashing error, not related to US accounts.
It was late when I wrote that code... :D

**Comment by zanix** [comment]
> A hashing error, not related to US accounts
> 
> It was late when I wrote that code... im sorry :D

It's all good, glad to help debug where I can.
I just tested double hashing the password in Postman and I got a good response this time.
I was also able to add my litterbox in HA as well.

Thanks for making this and getting past this login issue!

**Comment by torquadon** [comment]
Thank you very much for sorting it out, much appreciated.
