### ISSUE TITLE
Not all states being represented

### ISSUE THREAD

**Issue by sliwma** [timniklas/hass-neakasa#36]
Hey, thanks for writing the integration.
I found an issue, at least "upside down" status is missing (showed as "unknown").

**Comment by timniklas** [comment]
Should be fixed, please test it if you can.
Thanks for your feedback

**Comment by sliwma** [comment]
Hey, when the litterbox is upside down, I still get "unknown" status.
